# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaards', '0002_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='usablity_rating',
            new_name='usability_rating',
        ),
    ]
